Api/index.js
Api/src/db.js
Api/src/routes/index.js
Api/src/server.js

configuracion basica del servidor con express, cors y rutas

serverConfig_routesConfig

---

Api/src/db.js
Api/src/models/Article.js
Api/src/models/Category.js
Api/src/models/Review.js
Api/src/models/ShoppingCart.js
Api/src/models/User.js

Se terminaron los modelos de la base de datos y las relaciones entre tablas

Terminado modelos base de datos

---

Api/src/controllers/getFill.js
Api/src/routes/index.js

obtencion de todos los datos de articulos

---

Api/eslint.config.mjs
Api/index.js
Api/package-lock.json
Api/package.json
Api/src/db.js
Api/src/models/Article.js
Api/src/models/Category.js
Api/src/models/Review.js
Api/src/models/ShoppingCart.js
Api/src/models/User.js
Api/src/routes/index.js
Api/src/server.js

ahora prettier funciona correctamente,  ajua

ya implemete en el back

---

Api/src/controllers/getById.js

cambio en getById query a params

Recibido por params

---

Client/src/App.jsx
Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Cards/Cards.css
Client/src/components/Cards/Cards.jsx
Client/src/components/Form/Form.css
Client/src/components/Form/Form.jsx
Client/src/components/Landing/Landing.jsx

se hizo un estilado del landing y del home

configuracion del home

---

Client/package-lock.json
Client/package.json
Client/src/components/Footer/Footer.jsx
Client/src/components/Landing/Landing.css
Client/src/components/Landing/Landing.jsx

a landing page agregue mas estilo, también agregue un footer, el cual modularice, ahora trabajare mas en eso pero en otra rama para poder agregarlo a las otras paginas y agregare mas estilos al footer y contenido
tambien instale Font Awesome Para agregar iconos por ejemplo de las redes sociales. y agregue que al dar click mande al link de la red sociales

agregue estilos css

---

Client/eslint.config.js
Client/src/App.jsx
Client/src/components/Auth0/Profile/Profile.css
Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Card/Card.jsx
Client/src/components/Card/card.css
Client/src/components/Cards/Cards.css
Client/src/components/Cards/Cards.jsx
Client/src/components/Cloudinary/Cloudinary.jsx
Client/src/components/Detail/Detail.css
Client/src/components/Detail/Detail.jsx
Client/src/components/Footer/Footer.css
Client/src/components/Footer/Footer.jsx
Client/src/components/Form/Form.css
Client/src/components/Form/Form.jsx
Client/src/components/Home/Home.css
Client/src/components/Home/Home.jsx
Client/src/components/Landing/Landing.css
Client/src/components/Nav/Nav.css
Client/src/components/Nav/Nav.jsx
Client/src/components/SearchBar/SearchBar.jsx
Client/src/components/Validation/Validation.jsx
Client/src/components/pagination/Pagination.css
Client/src/components/pagination/Pagination.jsx
Client/src/index.css

ya agregue el footer en todas las rutas, a mi se me muestra todo correctamente pero igual dale una checada si puedes, ahorita es provisional el diseño ya que ya tengo uno pensado

footer all pages

---

Client/package-lock.json
Client/package.json
Client/src/components/Home/Home.jsx
Client/src/components/SearchBar/SearchBar.jsx
Client/src/main.jsx
Client/src/redux/actionTypes.js
Client/src/redux/actions.js
Client/src/redux/reducer.js
Client/src/redux/store.js

Al hacer este merge, se debe instalar de nuevo las dependencias debido a la adicion de nuevas dependencias como redux, redux-toolkit

Add filter front

---

Client/src/components/Auth0/Profile/Profile.css
Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Form/Form.css
Client/src/components/Nav/Nav.css
Client/src/components/pagination/Pagination.css
Client/src/index.css

css de profile nav pagination

---

Client/src/components/SearchBar/SearchBar.css
Client/src/components/SearchBar/SearchBar.jsx

se le creo estilos al buscador

creacion de estilos al buscador

---

Api/src/controllers/getSize.js
Api/src/routes/index.js

Creating new getSize file to obtain all sizes

Creating getSize

---

Api/src/controllers/controllersUser/getUserByEmail.js
Api/src/routes/detailRoutes/routerUser.js

Feat get user by email

---

Api/src/controllers/controllersCart/addArticleCart.js

Fix error controller addArticleCart

Fix controller addArticleCart

---

Client/src/App.jsx
Client/src/components/Products/Products.jsx

agregue products

---

Client/src/components/SearchBar/SearchBar.jsx

cofiguracion del buscador, ahora podes buscar con la tecla enter y se deja lo que estas buscando

fix-searchbar

---

Client/src/components/Footer/Footer.jsx
Client/src/components/Home/Home.jsx

cambio de una sola linea de codigo

Img-footer

---

Client/src/components/Detail/Detail.css
Client/src/components/Detail/Detail.jsx

ya debería estar en orden el código dentro de detail.jsx

FIX-Detail

---

Client/src/components/Auth0/Logout/Logout.jsx
Client/src/components/Auth0/Logout/logout.css
Client/src/components/Auth0/Profile/Profile.css
Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Card/Card.jsx
Client/src/components/Card/card.css
Client/src/components/Cards/Cards.css
Client/src/components/Cards/Cards.jsx

cambios en el profile, logaut, en cards

Fix-profile-styles-cards

---

Client/src/components/Products/Products.css
Client/src/components/Products/Products.jsx
Client/src/components/SearchBar/SearchBar.jsx

se hizo cambio del buscador, ahora te redireeciona a products, tambien el filtro cuando no hay nada que coincida con el filtro me tirara una alerta de error

fix-search-filter

---

Client/src/components/Home/Home.css
Client/src/components/Home/Home.jsx

ahora se maneja el tipo de letra roboto en home

cambie font en home

---

Client/src/components/Footer/Footer.css
Client/src/components/Footer/Footer.jsx

ya hice el cambio de fuente en footer, ahora se trabaja con roboto al igual que toda la pagina
tambien hice el cambio de href a links

cambio de fuente en footer

---

Client/src/components/Nav/Nav.css
Client/src/components/Nav/Nav.jsx

Logo Navbar

---

Api/src/controllers/controllersCart/desactivateShoppingCart.js

Correccion para desactivar el carrito

discount stock article

---

Client/src/App.css
Client/src/App.jsx

arreglo del footer para todas las rutas

fix-style-app

---

Client/src/components/Nav/Nav.jsx

ahora en el nav se ve la imagen de la persona que usa el profile y no un icon

nav-profile

---

Client/src/components/Form/Form.jsx

Fix alert-form

---

.vscode/settings.json
Client/src/components/Cloudinary/Cloudinary.jsx
Client/src/components/Form/Form.css
Client/src/components/Form/Form.jsx

ya di estilos a form, hice un cambio en los estados de error, deje inicializado el estado que te lanzaba el mensaje de que campos eran obligatorios, por que si no los dejan inicializados, cuando empezabas a escribir aparecían todos, así evitamos eso. me gustaría que no desaparezca cuando empiezas a llenar ese campo pero eso es preferencia mía, si lo veo necesario lo hare en otra rama

style-form

---

Client/src/components/Footer/Footer.jsx

a las redes sociales fie agregado _blank para que al dar clic se abriera en otra pestaña
además hice corrección en la traducción de ciertas palabras
por ultimo cambie la ruta de about, la intercambie por /form

_blank agregado

---

Api/src/controllers/controllersCart/addArticleCart.js

Añadiendo opcion de agregar tallas cuando se agrege un articulo nuevo

Feat addArticles sizes

---

Api/src/controllers/controllersCart/addArticleCart.js

Modificacion de controlador addArticleCart añadiendo la nueva caracteriztica que permite obtener las tallas por ariticulo

Add new sizes addArticle

---

Api/src/controllers/controllersCart/addArticleCart.js
Api/src/controllers/controllersCart/removeArticleCart.js

Mejorando el sistema de descontar el subtotal del carrito de compras cada ves que se añade o remueve un articulo

Fix subtotal remove article cart

---

Client/src/components/Detail/Detail.css
Client/src/components/Detail/Detail.jsx

hice los cambios para que el botón se deshabilite cuando no hay stock de una talla, para lograr eso hice cambios en el const de body, además agregue líneas a cada botón para deshabilitarlo, y por ultimo agregue CSS al botón cuando esta deshabilitado

Fix detail stock size

---

Client/src/components/Form/Form.jsx
Client/src/components/Validation/Validation.jsx

Add size stock form

---

Client/src/App.jsx
Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Card/CardEdit.jsx
Client/src/components/Card/cardEdit.css
Client/src/components/Cards/CardsEdit.jsx
Client/src/components/EditProducts/EditProducts.jsx

ahora muestra el botón para editar productos y renderiza el componente
cabe mencionar que no se aplicaron estilos, solo se aplico funcionalidad en profile, aun que a cardEdit.css si se le aplicaron estilos

Add edit product

---

Client/src/components/SearchBar/SearchBar.jsx

ahora se actualiza mientras se escribe

fix-searchBar-update

---

Client/package-lock.json
Client/src/components/EditProducts/EditProducts.jsx

se agrego el filtrado, esta funcionado al 90% ya que al estar en isActive y desactivas el producto se sigue mostrando ahi, me gustaría que sea actualice solo y lo deje de mostrar, para notar el cambio tienes que cambiar de filtrado y volver al mismo,

segrego el filtrado isactive

---

Api/src/controllers/controllersReview/getAllReviews.js
Api/src/routes/detailRoutes/routerReview.js

Nuevo controlador obtiene una lista de reviews con el mismo funcionamiento de las listas de usuarios, pueden acceder por orden de review o fecha de creacion

Feat getAllReviews list

---

Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Card/CardEdit.jsx
Client/src/components/Card/CardUsers.css
Client/src/components/Card/CardUsers.jsx
Client/src/components/ListUsers/ListUsers.jsx
Client/src/components/SearchBar/UsersSearchBar.jsx

hice cambios en los componentes que se renderizan en profile, también hice cambios de idioma.
Aun el footer se renderiza mal tengo eso pendiente

styleProfile

---

Api/src/controllers/controllersCart/addArticleCart.js
Client/src/components/CheckoutForm/CheckoutForm.css
Client/src/components/CheckoutForm/CheckoutForm.jsx

Se añade la direcion de usuario y opcion de modificar la direccion, tambien se corrige error al añadir articulo por primera ves no redondeaba la cifra a dos decimales

Fix addArticleCart and modify checkout form

---

Client/src/components/Detail/Detail.jsx

Añade la talla exacta cuando mando un articulo al carrito

Add size buy

---

Client/src/App.css
Client/src/components/Review/Review.jsx
Client/src/components/Review/createReview.css
Client/src/components/Review/createReview.jsx
Client/src/components/Review/review-list.css
Client/src/components/Review/reviewList.jsx

ya se estilizo todos los componentes relacionados a las reviews y se hicieron correcciones de idioma de español a ingles

stylereview

---

Client/src/App.jsx
Client/src/components/Auth0/Profile/Profile.jsx
Client/src/components/Form/Form.css
Client/src/components/Form/Form.jsx
Client/src/components/Nav/Nav.jsx

ya fue agregado el boton de form en profile, y se quito el boton de Form en nav

FormProfileAdmin

---

Client/src/components/Review/reviewAdmin.jsx

fix-idioma

---

Client/src/components/Auth0/Profile/Profile.css
Client/src/components/Auth0/Profile/Profile.jsx

agregue estilos a editar profile

style-editprofile
